---

- name: create minio-user group
  group:
    name: minio-user
    system: yes

- name: create minio-user user
  user:
    name: minio-user
    group: minio-user
    create_home: no
    system: yes

- name: install cifs-utils
  dnf:
    name: cifs-utils
    state: latest

- name: mkdir /mnt/nas
  file:
    path: /mnt/nas
    state: directory

- name: mount /mnt/nas/
  mount:
    src: //192.168.1.1/share
    path: /mnt/nas
    fstype: cifs
    opts: "x-systemd.automount,x-systemd.device-timeout=30,_netdev,user=admin,pass={{ cifs_pass }},vers=2.0,uid=minio-user,gid=minio-user"
    state: mounted

- name: mkdir /mnt/nas
  file:
    path: /mnt/nas/minio
    state: directory

- name: mkdir /opt/cert
  file:
    path: /opt/cert 

- name: copy key
  copy:
    src: /opt/cert/minio-1.localdomain.key
    dest: /opt/cert/minio-1.localdomain.key

- name: make key
  command:
    openssl rsa
    -in /opt/cert/minio-1.localdomain.key
    -out /opt/cert/private.key

- name: change permission
  file:
    path: /opt/cert/private.key
    owner: minio-user
    group: minio-user
    mode: 0400

- name: copy cert
  copy:
    src: /opt/cert/minio-1.localdomain.crt
    dest: /opt/cert/public.crt
    owner: minio-user
    group: minio-user
    mode: 0644

- name: get minio
  get_url:
    url: https://dl.min.io/server/minio/release/linux-amd64/archive/minio-20230120020544.0.0.x86_64.rpm
    dest: /tmp/minio.rpm

- name: install minio
  dnf:
    name: /tmp/minio.rpm

- name: put /etc/default/minio
  template:
    src: minio.j2
    dest: /etc/default/minio
    owner: root
    group: root
    mode: 0644
    remote_src: yes

- name: 9090 port open
  firewalld:
    zone: public
    port: 9090/tcp
    permanent: yes
    immediate: yes
    state: enabled

- name: 9000 port open
  firewalld:
    zone: public
    port: 9000/tcp
    permanent: yes
    immediate: yes
    state: enabled

- name: start minio
  systemd:
    name: minio
    state: restarted
    enabled: yes
